### ISSUE TITLE
Konsist CI

### ISSUE THREAD

**Issue by kigya** [kigya/Mindplex-Multiplatform#11]
Link Konsist to Github Actions. Example:

```yaml
name: Run Konsist lint rules
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-lint-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Konsist lint rules Gradle task
        run: ./gradlew :konsist:test
```
